/**
 * fis init — Scaffold artifact directories for a new project.
 */

import { mkdirSync, existsSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ARTIFACT_DIRS = [
  'artifacts/prd',
  'artifacts/trd',
  'artifacts/epics',
  'artifacts/stories',
  'artifacts/test-specs',
  'artifacts/tsd',
  'artifacts/plans',
  'artifacts/bugs',
  'artifacts/change-requests',
  'artifacts/personas',
  'artifacts/reviews',
  'artifacts/reports',
  'artifacts/visuals',
  '.fis/logs',
]

const README_CONTENT = `# Artifacts

Generated by fis-cli. Each artifact lives in its dedicated directory:

| Directory | Type | Producer Skill |
|---|---|---|
| prd/ | Product Requirements Document | /fis:ba:create-prd |
| trd/ | Technical Requirements Document | /fis:sa:design-trd |
| epics/ | Epic groupings | /fis:sa:decompose-epic |
| stories/ | User Stories with AC | /fis:sa:write-story |
| test-specs/ | Test Specifications | /fis:qa:write-test-spec |
| tsd/ | Test Strategy Document (project-level) | /fis:qa:design-tsd |
| plans/ | Implementation Plans (light) | /fis:dev:plan |
| bugs/ | Bug reports (light) | /fis:qa:bug-triage |
| change-requests/ | Change Requests (light) | /fis:ba:change-request |
| personas/ | Stakeholder + Three Amigos personas | /fis:ba:manage-personas |
| reviews/ | Three Amigos review reports | /fis:three-amigos:review-* |
| reports/ | Drift, scout, sa-review, code-review | (auto-generated) |
| visuals/ | Diagrams, screenshots, mockups | (manual + skills) |

DO NOT delete \`.fis/logs/\` — used for handoff-gate audit log.
`

export async function initCommand(args: string[]): Promise<void> {
  let target = process.cwd()
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--target' && args[i + 1]) {
      target = args[i + 1]
      i++
    }
  }

  console.log(`Initializing FIS AI Kit artifacts at: ${target}`)

  let created = 0
  let skipped = 0
  for (const dir of ARTIFACT_DIRS) {
    const full = join(target, dir)
    if (existsSync(full)) {
      skipped++
    } else {
      mkdirSync(full, { recursive: true })
      created++
    }
  }

  // Create README in artifacts/
  const readmePath = join(target, 'artifacts', 'README.md')
  if (!existsSync(readmePath)) {
    writeFileSync(readmePath, README_CONTENT)
  }

  // Create .fisrc.json with project config
  const configPath = join(target, '.fisrc.json')
  if (!existsSync(configPath)) {
    const config = {
      version: '0.1.0',
      project: {
        name: target.split('/').pop() || 'unknown',
        created: new Date().toISOString().slice(0, 10),
      },
      handoff_gate: {
        enabled: true,
      },
      three_amigos: {
        async_sla_hours: 24,
      },
    }
    writeFileSync(configPath, JSON.stringify(config, null, 2))
  }

  console.log(`✅ Created ${created} directories, skipped ${skipped} existing.`)
  console.log(`Next step: fis install (copy claude/ + templates/ into project)`)
}
